ansible_password: "{{ lookup('community.hashi_vault.vault_read', 'kv/data/ansible').data.data.password }}"
ansible_sudo_pass: "{{ lookup('community.hashi_vault.vault_read', 'kv/data/ansible').data.data.password_root }}"
ansible_ssh_private_key_file: "{{ lookup('community.hashi_vault.vault_read', 'kv/data/ansible').data.data.ssh_key_file }}"
