---
plugin: community.general.proxmox
url: "{{ lookup('community.hashi_vault.vault_read', 'kv/data/ansible').data.data.proxmox_url }}"
user: "{{ lookup('community.hashi_vault.vault_read', 'kv/data/ansible').data.data.proxmox_user }}"
token_id: "{{ lookup('community.hashi_vault.vault_read', 'kv/data/ansible').data.data.proxmox_token_id }}"
token_secret: "{{ lookup('community.hashi_vault.vault_read', 'kv/data/ansible').data.data.proxmox_token_secret }}"
validate_certs: false
want_facts: true
groups:
  proxmox_vms: "'standalone_vm' in (proxmox_tags_parsed | list)"
compose:
  ansible_host: proxmox_agent_interfaces | selectattr('name', 'match', '^en') | map(attribute='ip-addresses') | flatten | first | ansible.utils.ipaddr('address')
  mac_addr: proxmox_net0.virtio | ansible.utils.macaddr
filters:
  - "'nas_vm' not in (proxmox_tags_parsed | list)"
